learner:
  name: SupervisedLearner
  args:
model:
  name: ModelWithLoss
  args:
    model:
      freeze_backbone: False
      name: resnext50_32x4d
      from_pretrained: True
    loss:
      name: FocalLoss
      args: Null
optimizer:
  name: Adam
  args:
    lr: 0.0001
metric:
  - name: Accuracy
    args: Null
scheduler:
  name: StepLR
  args:
    step_size: 3
    gamma: 0.2
    last_epoch: -1
dataset:
  name:
  trainval: True
  train:
    name: LeafDatasetAdvance
    args:
      data_dir: data/train_images/
      csv_path: lists/train.csv
      IMG_SIZE: 512
      is_train: True
    loader:
      name: DataLoader
      args:
        batch_size: 16
        shuffle: True
        drop_last: True
  val:
    name: LeafDatasetAdvance
    args:
      data_dir: data/train_images/
      csv_path: lists/val.csv
      IMG_SIZE: 512
      is_train: False
    loader:
      name: DataLoader
      args:
        batch_size: 16
        shuffle: True
