opts:
  pretrained: null
  id: default

  debug: True # if debug = true, model will not save checkpoint
  demo: False
  resume: False
  test: False

  nepochs: 20
  batch_size: 10

  gpus: 0,1,2,3
  num_workers: 4
  fp16: True

  val_step: 1
  log_step: 1

  num_iters: -1
  save_dir: ./tmptmp
  verbose: True
  seed: 123
